package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off
javascripts:
  jquery:
    - public/javascripts/jquery.min.js
  main:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/fileuploader-custom.js
    - public/javascripts/isport.js
    - public/javascripts/showNotifications.js
    - public/javascripts/jquery.autoresize.min.js

  scroll_page:
    - public/javascripts/scrollPage.js
  show_photo:
    - public/javascripts/showPhoto.js
  show_avatar:
    - public/javascripts/showAvatar.js
  jqueryui:
    - public/javascripts/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js
    - public/javascripts/colorbox/jquery.colorbox.js
    - public/javascripts/jquery-ui-1.8.13/development-bundle/ui/i18n/jquery.ui.datepicker-zh-CN.js
    - public/javascripts/autosuggest/jquery.autoSuggest.js
    - public/javascripts/jquery.timeago.js
  friend_select:
    - public/javascripts/fcbk/fcbklistselection.js
    - public/javascripts/fcbk/friend_select.js

stylesheets:
  blueprint:
    - public/stylesheets/css/plugins/blueprint/screen.css
    
  default:
    - public/stylesheets/css/general/application/application.css
    - public/stylesheets/css/plugins/fileuploader.css
    - public/stylesheets/css/general/headings/header.css
    - public/stylesheets/css/special_pages/home/index.css
    - public/stylesheets/css/special_pages/devise_sessions/new.css
    - public/javascripts/jquery-ui-1.8.13/css/custom-theme/jquery-ui-1.8.13.custom.css
    - public/stylesheets/css/plugins/colorbox.css
    - public/stylesheets/css/plugins/fcbklistselection.css
    - public/stylesheets/css/plugins/autoSuggest.css
    - public/stylesheets/css/special_pages/conversations/index.css
    - public/stylesheets/css/special_pages/status_messages/status_message.css

  forms:
    - public/stylesheets/css/general/forms/events_form.css

  sepcial_pages_events_index:
    - public/stylesheets/css/special_pages/events/index.css
  sepcial_pages_events_show:
    - public/stylesheets/css/special_pages/events/show.css
  sepcial_pages_events_edit:
    - public/stylesheets/css/special_pages/events/edit.css
  sepcial_pages_events_common:
    - public/stylesheets/css/special_pages/events/common.css
  sepcial_pages_events_my_event_item:
    - public/stylesheets/css/special_pages/events/my_event_item.css

  sepcial_pages_items_show:
    - public/stylesheets/css/special_pages/items/show.css
 
