package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off
javascripts:
  jquery:
    - public/javascripts/jquery.min.js
  main:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/fileuploader-custom.js
    - public/javascripts/view.js
    - public/javascripts/facebox.js
  jqueryui:
    - public/javascripts/jquery-ui-1.8.13/js/jquery-1.5.1.min.js
    - public/javascripts/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js

stylesheets:
  blueprint:
    - public/stylesheets/css/plugins/blueprint/ie.css
    - public/stylesheets/css/plugins/blueprint/screen.css
    
  default:
    - public/stylesheets/css/general/application/application.css
    - public/stylesheets/css/general/ui/ui.css
    - public/stylesheets/css/plugins/fileuploader.css
    - public/stylesheets/css/plugins/facebox.css
    - public/stylesheets/css/general/headings/header.css
    - public/javascripts/jquery-ui-1.8.13/css/custom-theme/jquery-ui-1.8.13.custom.css
  forms:
    - public/stylesheets/css/general/forms/events_form.css

 
