package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off
javascripts:
  jquery:
    - public/javascripts/jquery.min.js
  main:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/fileuploader-custom.js
    - public/javascripts/isport.js
    - public/javascripts/showNotifications.js
    - public/javascripts/jquery.autoresize.min.js
    - public/javascripts/search.js
    - public/javascripts/jquery.autocomplete-custom.js
    - public/javascripts/keycodes.js

  google_analytics:
    - public/javascripts/google_analytics.js
  status_message:
    - public/javascripts/statusMessage.js
  scroll_page:
    - public/javascripts/scrollPage.js
  show_photo:
    - public/javascripts/showPhoto.js
  show_avatar:
    - public/javascripts/showAvatar.js
  jqueryui:
    - public/javascripts/jquery-ui-1.8.16/js/jquery-ui-1.8.16.custom.min.js
    - public/javascripts/colorbox/jquery.colorbox.js
    - public/javascripts/jquery-ui-1.8.16/development-bundle/ui/i18n/jquery.ui.datepicker-zh-CN.js
    - public/javascripts/autosuggest/jquery.autoSuggest.js
    - public/javascripts/jquery.timeago.js
  jquery_form:
    - public/javascripts/jquery.form.js
  jquery_validation:
    - public/javascripts/jquery.validate.js
  jquery_fancybox:
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.pack.js
  friend_select:
    - public/javascripts/fcbk/fcbklistselection.js
    - public/javascripts/fcbk/friend_select.js
  google_map:
    - public/javascripts/mark_on_google_map.js

stylesheets:
  jquery_fancybox_css:
    - public/javascripts/fancybox/jquery.fancybox-1.3.4.css
  blueprint:
    - public/stylesheets/css/plugins/blueprint/screen.css
  wizard_steps:
    - public/stylesheets/css/general/common/wizard_steps.css
  common_index:
    - public/stylesheets/css/general/common/index.css
  common_vertical_nav:
    - public/stylesheets/css/general/common/vertical_nav.css
  common_people_select:
    - public/stylesheets/css/general/common/people_select.css
    
    
  default:
    - public/stylesheets/css/general/application/application.css
    - public/stylesheets/css/plugins/fileuploader.css
    - public/stylesheets/css/general/headings/header.css
    - public/stylesheets/css/general/footer/footer.css
    - public/stylesheets/css/special_pages/devise_sessions/new.css
    - public/javascripts/jquery-ui-1.8.16/css/pepper-grinder/jquery-ui-1.8.16.custom.css
    - public/stylesheets/css/plugins/colorbox.css
    - public/stylesheets/css/plugins/fcbklistselection.css
    - public/stylesheets/css/plugins/autoSuggest.css
    - public/stylesheets/css/special_pages/conversations/index.css
    - public/stylesheets/css/special_pages/status_messages/status_message.css
    - public/stylesheets/css/special_pages/people/show.css
    - public/stylesheets/css/special_pages/people/show_person_details.css
    - public/stylesheets/css/general/common/autocomplete.css

  forms:
    - public/stylesheets/css/general/forms/events_form.css

  forum_large:
    - public/stylesheets/css/general/application/forum_large.css

  sepcial_pages_events_index:
    - public/stylesheets/css/special_pages/events/index.css
  sepcial_pages_events_show:
    - public/stylesheets/css/special_pages/events/show.css
  sepcial_pages_events_edit:
    - public/stylesheets/css/special_pages/events/edit.css
  sepcial_pages_events_common:
    - public/stylesheets/css/special_pages/events/common.css
  special_pages_events_comments:
    - public/stylesheets/css/special_pages/events/comments.css
  sepcial_pages_events_filtered:
    - public/stylesheets/css/special_pages/events/filtered.css
  sepcial_pages_events_my_event_item:
    - public/stylesheets/css/special_pages/events/my_event_item.css
  sepcial_pages_events_hottest:
    - public/stylesheets/css/special_pages/events/hot_event.css
  sepcial_pages_events_new_event_panel:
    - public/stylesheets/css/special_pages/events/new_event_panel.css
  sepcial_pages_events_in_audit:
    - public/stylesheets/css/special_pages/events/in_audit.css
  sepcial_pages_events_upload_pic:
    - public/stylesheets/css/special_pages/events/upload_pic.css

  special_pages_items_show:
    - public/stylesheets/css/special_pages/item/show.css
  
  special_pages_items_index:
    - public/stylesheets/css/special_pages/item/index.css

  special_pages_items_myitems:
    - public/stylesheets/css/special_pages/item/myitems.css

  special_pages_items_commom:
    - public/stylesheets/css/special_pages/item/commom.css


  sepcial_pages_groups_form:
    - public/stylesheets/css/special_pages/groups/form.css
  sepcial_pages_groups_common:
    - public/stylesheets/css/special_pages/groups/common.css
  sepcial_pages_groups_show:
    - public/stylesheets/css/special_pages/groups/show.css
  sepcial_pages_groups_index:
    - public/stylesheets/css/special_pages/groups/index.css
  sepcial_pages_groups_hottest:
    - public/stylesheets/css/special_pages/groups/hottest.css
  sepcial_pages_groups_edit:
    - public/stylesheets/css/special_pages/groups/edit.css
  sepcial_pages_groups_events:
    - public/stylesheets/css/special_pages/groups/events.css
  special_pages_group_panel:
    - public/stylesheets/css/special_pages/groups/group_panel.css

  special_pages_topic_form:
    - public/stylesheets/css/special_pages/topics/form.css
  special_pages_topic_show:
    - public/stylesheets/css/special_pages/topics/show.css
  special_pages_topic_index:
    - public/stylesheets/css/special_pages/topics/index.css
  special_pages_topic_comments:
    - public/stylesheets/css/special_pages/topics/comments.css
  special_pages_topic_recent:
    - public/stylesheets/css/special_pages/topics/recent.css

  special_pages_welcome:
    - public/stylesheets/css/special_pages/welcome/index.css

  special_pages_registration_new:
    - public/stylesheets/css/special_pages/registration/new.css
  special_pages_registration_reset_password:
    - public/stylesheets/css/special_pages/registration/reset_password.css

  sepcial_pages_users_selectinterests:
    - public/stylesheets/css/special_pages/users/select_interests.css
  sepcial_pages_people_edit_interests:
    - public/stylesheets/css/special_pages/people/edit_interests.css

  sepcial_pages_site_info_common:
    - public/stylesheets/css/special_pages/site_info/common.css

  sepcial_pages_friends_common:
    - public/stylesheets/css/special_pages/friends/common.css

  sepcial_pages_site_admin_common:
    - public/stylesheets/css/special_pages/site_admin/common.css

  sepcial_pages_home_index:
    - public/stylesheets/css/special_pages/home/index.css

  sepcial_pages_site_posts_index:
    - public/stylesheets/css/special_pages/site_posts/index.css
  sepcial_pages_site_posts_form:
    - public/stylesheets/css/special_pages/site_posts/form.css
  sepcial_pages_site_post_block:
    - public/stylesheets/css/special_pages/site_posts/post_block.css

  sepcial_pages_pics_index:
    - public/stylesheets/css/special_pages/pics/index.css
