package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off
javascripts:
  jquery:
    - public/javascripts/jquery.min.js
  main:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/fileuploader-custom.js
    - public/javascripts/facebox.js
    - public/javascripts/html5.js
  jqueryui:
    - public/javascripts/jquery-ui-1.8.13/js/jquery-ui-1.8.13.custom.min.js

stylesheets:
  default:
    - public/stylesheets/application.css
    - public/stylesheets/ui.css
    - public/stylesheets/fileuploader.css
    - public/stylesheets/facebox.css
    - public/stylesheets/header.css
    - public/javascripts/jquery-ui-1.8.13/css/custom-theme/jquery-ui-1.8.13.custom.css

 
