package_assets: on
embed_assets: on
compress_assets: on
gzip_assets: off
javascripts:
  jquery:
    - public/javascripts/jquery.min.js
  main:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/fileuploader-custom.js
    - public/javascripts/view.js
    - public/javascripts/facebox.js

stylesheets:
  default:
    - public/stylesheets/application.css
    - public/stylesheets/ui.css
    - public/stylesheets/fileuploader.css
    - public/stylesheets/facebox.css
 
